Exception in thread "Reference Handler" java.lang.IllegalMonitorStateException
	at java.lang.Object.notifyAll(Native Method)
	at java.lang.ref.ReferenceQueue.enqueue(ReferenceQueue.java:73)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:217)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.remove(ArrayList.java:873)
	at org.nlogo.job.JobThread.compact(JobThread.scala:188)
	at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:67)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
	at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:66)
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.nlogo.job.JobThread.compact(JobThread.scala:187)
	at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:67)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
	at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:66)
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.remove(ArrayList.java:873)
	at org.nlogo.job.JobThread.compact(JobThread.scala:188)
	at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:67)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
	at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:66)
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.remove(ArrayList.java:873)
	at org.nlogo.job.JobThread.compact(JobThread.scala:188)
	at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:67)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
	at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:66)
Error in checkForRemoteErrors(val) : 
  4 nodes produced errors; first error: java.lang.Exception: Found unknown datatype: null
Calls: nl_run ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted
srun: error: cg5-15: task 0: Exited with exit code 1
